### ISSUE TITLE
I've encountered some problems. Can you help me?

### ISSUE THREAD

**Issue by Le0v1n** [shyammarjit/GA-MLP-for-Emotion-Recognition#1]
1. Is the data Python data officially provided by DEAP, which has only two keys: `labels` & `data` (`data_preprocessed_python` folder, the data name inside is `s01.dat`, and the size is `98.44MB`)?
2. Can you provide a version of the Python library?

Looking forward to your reply, thank you😊.

**Comment by shyammarjit** [comment]
Yes, DEAP officially released s01.dat (python data) which has two keys: `labels` & `data`. I have worked with `Python 3.10.9`. Python3 should work without an issue.

Thank you for showing your interest in my work. If you have any doubts or queries please feel free to ask me by mail at shyam.marjit@iiitg.ac.in or marjitshyam@gmail.com.

**Comment by Le0v1n** [comment]
Thank you for your reply. I encountered the following problem when I ran the code. I suspect it is a problem with the mne library version. Codes are as follows:
```python
    ica = ICA(n_components=N_C, random_state=97, verbose=False)
    ica.fit(raw_data)
    # https://mne.tools/stable/generated/mne.preprocessing.find_eog_events.html?highlight=find_eog_#mne.preprocessing.find_eog_events
    eog_indices, eog_scores = ica.find_bads_eog(raw_data.copy(), ch_name='Fp1', verbose=None)
    a = abs(eog_scores).tolist()
    if (droping_components == 'one'):
        ica.exclude = [a.index(max(a))]
```

The question is: 

```
Traceback (most recent call last):
  File "/data/data_01/lijiandong/MultimodalEmotionRecognition/2_CNN/third_part_codes/EEG-Emotion-Recognition-IRIA-2021/main.py", line 321, in <module>
    train_data, four_train_label, test_data, four_test_label = get_data(subject_no)
  File "/data/data_01/lijiandong/MultimodalEmotionRecognition/2_CNN/third_part_codes/EEG-Emotion-Recognition-IRIA-2021/main.py", line 299, in get_data
    data = signal_pro(data)
  File "/data/data_01/lijiandong/MultimodalEmotionRecognition/2_CNN/third_part_codes/EEG-Emotion-Recognition-IRIA-2021/main.py", line 255, in signal_pro
    input_data[i] = SignalPreProcess(input_data[i].copy())
  File "/data/data_01/lijiandong/MultimodalEmotionRecognition/2_CNN/third_part_codes/EEG-Emotion-Recognition-IRIA-2021/main.py", line 232, in SignalPreProcess
    eog_indices, eog_scores = ica.find_bads_eog(raw_data.copy(), ch_name='Fp1', verbose=None)
  File "<decorator-gen-400>", line 22, in find_bads_eog
  File "/root/anaconda3/envs/emo/lib/python3.9/site-packages/mne/preprocessing/ica.py", line 1546, in find_bads_eog
    self.labels_['eog'], scores = self._find_bads_ch(
  File "/root/anaconda3/envs/emo/lib/python3.9/site-packages/mne/preprocessing/ica.py", line 1173, in _find_bads_ch
    scores += [self.score_sources(
  File "<decorator-gen-397>", line 22, in score_sources
  File "/root/anaconda3/envs/emo/lib/python3.9/site-packages/mne/preprocessing/ica.py", line 1115, in score_sources
    scores = _find_sources(sources, target, score_func)
  File "/root/anaconda3/envs/emo/lib/python3.9/site-packages/mne/preprocessing/ica.py", line 2116, in _find_sources
    raise ValueError('%s is not a valid score_func.' % score_func)
ValueError: pearsonr is not a valid score_func.
```

The specific question seems `ValueError: pearsonr is not a valid score_func.`. The version of my mne is: 

```bash
mne                           0.22.0
scikit-learn                  1.3.0
```

Could you please show me the specific version of the code you were running at that time? Thank you so much!

**Comment by shyammarjit** [comment]
Please use the latest version of `MNE` for example version 1.5.1. 
I don't have the conda environment, I removed it. Sorry about that.

**Comment by Le0v1n** [comment]
Thanks for your reply!

**Comment by shyammarjit** [comment]
> Thanks for your reply!

Please let me know if you have any more issues.
